# Generated by Django 3.2.6 on 2021-08-05 02:45

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=150)),
                ('date_education', models.CharField(max_length=150)),
                ('description_education', models.CharField(max_length=255)),
                ('experiences', models.CharField(max_length=150)),
                ('date_experiences', models.CharField(max_length=150)),
                ('description_experiences', models.CharField(max_length=255)),
                ('language_name', models.CharField(max_length=150)),
                ('percent', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resume',
            },
        ),
        migrations.DeleteModel(
            name='codingSkill',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
    ]
