# Generated by Django 3.2.6 on 2021-08-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='percent',
            new_name='date_education',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=50)),
                ('description_education', models.CharField(max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.resume')),
            ],
        ),
    ]
