# Generated by Django 3.2.6 on 2021-08-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210805_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='date_education',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
