# Generated by Django 3.2.6 on 2021-08-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_education_date_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
