# Generated by Django 3.2.6 on 2021-08-05 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_otherskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiences', models.CharField(blank=True, max_length=50)),
                ('date_experiences', models.CharField(max_length=150)),
                ('description_experiences', models.CharField(max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.resume')),
            ],
        ),
    ]
