# Generated by Django 3.2.6 on 2021-08-06 08:09

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_en', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, upload_to='images/blog/%Y/%m/%d/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=150)),
                ('date_education', models.CharField(max_length=150)),
                ('description_education', models.CharField(max_length=255)),
                ('experiences', models.CharField(max_length=150)),
                ('date_experiences', models.CharField(max_length=150)),
                ('description_experiences', models.CharField(max_length=255)),
                ('language_name', models.CharField(max_length=150)),
                ('percent', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('update_at', django_jalali.db.models.jDateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resume',
            },
        ),
        migrations.AlterModelOptions(
            name='setting_en',
            options={},
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(blank=True, max_length=50)),
                ('percent', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_en.resume')),
            ],
        ),
        migrations.CreateModel(
            name='otherSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=50)),
                ('percent', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_en.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiences', models.CharField(blank=True, max_length=50)),
                ('date_experiences', models.CharField(max_length=150)),
                ('description_experiences', models.CharField(max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_en.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=50)),
                ('date_education', models.CharField(max_length=150)),
                ('description_education', models.CharField(max_length=255)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_en.resume')),
            ],
        ),
    ]
