# Generated by Django 3.2.6 on 2021-08-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_en', '0002_auto_20210806_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blog_en',
        ),
        migrations.RenameModel(
            old_name='Education',
            new_name='Education_en',
        ),
        migrations.RenameModel(
            old_name='Experience',
            new_name='Experience_en',
        ),
        migrations.RenameModel(
            old_name='otherSkill',
            new_name='otherSkill_en',
        ),
        migrations.RenameModel(
            old_name='Resume',
            new_name='Resume_en',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skill_en',
        ),
        migrations.RenameField(
            model_name='education_en',
            old_name='resume',
            new_name='resume_en',
        ),
        migrations.RenameField(
            model_name='experience_en',
            old_name='resume',
            new_name='resume_en',
        ),
        migrations.RenameField(
            model_name='otherskill_en',
            old_name='resume',
            new_name='resume_en',
        ),
        migrations.RenameField(
            model_name='skill_en',
            old_name='resume',
            new_name='resume_en',
        ),
    ]
